# Developpment compose configuration
# DO NOT USE IN PRODUCTION

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://clicketing:123456@postgres/clicketing
    volumes:
      # Bind-mount the app project folder into the container
      - type: bind
        source: .
        target: /app
    ports:
      - 3000:3000

volumes:
  database:
