FROM node:18-alpine3.18

# the root folder will be mounted at /app in the container
WORKDIR /app

# use "node" user with UID/GID 1000 (avoid permission issues with root)
USER node

ENV ADMIN_TOKEN=1234
ENV JWT_SECRET=1234

# install dependencies and run in watch mode
CMD npm install && npx prisma generate && npm run dev