# Developpment compose configuration
# DO NOT USE IN PRODUCTION

include:
  - directus-config/directus.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      # Bind-mount the app project folder into the container
      - type: bind
        source: .
        target: /app

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    ports:
      - 80:80

volumes:
  database:
