name: 'Lint PR for conventional commits'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited # run when the PR title is changed

jobs:
  check-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-commits:
    name: Run commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required to read the commit history
      - uses: wagoid/commitlint-github-action@v5
